before:
  hooks:
    - go mod tidy
builds:
  - binary: monorepo-diff-buildkite-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - netbsd
      - openbsd
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le

checksum:
  name_template: 'checksums.txt'

archives:
  - format: 'binary'
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
