name: Monorepo Diff
description: Trigger pipelines on changes in watched folders
author: https://github.com/monebag
requirements:
  - git
configuration:
  properties:
    diff:
      type: string
    log_level:
      type: string
    interpolation:
      type: boolean
    env:
      type: array
    notify:
      type: [array]
      properties:
        email:
          type: string
        webhook:
          type: string
        pagerduty_change_event:
          type: string
        basecamp_campfire:
          type: string
        github_commit_status:
          type: object
          properties:
            context:
              type: string
        slack:
          type: string
        if:
          type: string
    watch:
      type: array
      properties:
        path:
          type: [string, array]
          minimum: 1
        config:
          type: object
          properties:
            command:
              type: string
            trigger:
              type: string
            soft_fail:
              type: [object, boolean]
            notify:
              type: [array]
              properties:
                basecamp_campfire:
                  type: string
                github_commit_status:
                  type: object
                  properties:
                    context:
                      type: string
                slack:
                  type: string
                if:
                  type: string
            async:
              type: boolean
            label:
              type: string
            build:
              type: object
              properties:
                message:
                  type: string
                commit:
                  type: string
                branch:
                  type: string
                env:
                  type: array
                meta_data:
                  type: object
            agents:
              type: object
              properties:
                queue:
                  type: string
              additionalProperties:
                type: string
            artifacts:
              type: array
            env:
              type: array
    wait:
      type: boolean
    hooks:
      type: array
      properties:
        command:
          type: string
  required:
    - watch

# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite-plugins/buildkite-plugin-linter/master/lib/plugin-yaml-schema.yml
