name: Monorepo Diff
description: Trigger pipelines on changes in watched folders
author: https://github.com/monebag
requirements:
  - git
configuration:
  properties:
    diff:
      type: string
    log_level:
      type: string
    interpolation:
      type: boolean
    env:
      type: array
    watch:
      type: array
      properties:
        path:
          type: [string, array]
          minimum: 1
        config:
          type: object
          properties:
            command:
              type: string
            trigger:
              type: string
            async:
              type: boolean
            label:
              type: string
            build:
              type: object
              properties:
                message:
                  type: string
                commit:
                  type: string
                branch:
                  type: string
                env:
                  type: array
            agents:
              type: object
              properties:
                queue:
                  type: string
              additionalProperties:
                type: string
            artifacts:
              type: array
            env:
              type: array
    wait:
      type: boolean
    hooks:
      type: array
      properties:
        command:
          type: string
  required:
    - watch
