steps:
  - label: ":lint-roller: Lint"
    plugins:
      - docker-compose#v3.3.0:
          run: lint
  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v3.3.0:
          run: tests
  - label: "Triggering pipelines"
    plugins:
      - chronotc/monorepo-diff#${BUILDKITE_COMMIT}:
          diff: "cat ./e2e/one-match-one-miss"
          watch:
            - path: "foo-service/"
              config:
                trigger: "foo-service"
            - path: "hello-service/"
              config:
                trigger: "hello-service"
          wait: true

