#!/bin/bash
set -euo pipefail

arch="$(arch)"
arm=("arm armhf aarch64 aarch64_be armv6l armv7l armv8l arm64e") # arm64
amd=("x86 x86pc i386 i686 i686-64 x64 x86_64 x86_64h athlon")    # amd64
if [[ "${arm[*]}" =~ ${arch} ]]; then
  arch="arm64"
elif [[ "${amd[*]}" =~ ${arch} ]]; then
  arch="amd64"
fi

plugin=${BUILDKITE_PLUGINS:-""}
version=$(echo $plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".*//')
kernel=$(uname -s | awk '{print tolower($0)}')
allowed=("linux darwin")
if ! [[ "${allowed[*]}" =~ ${kernel} ]]; then
  exit 1
fi

repo="https://github.com/chronotc/monorepo-diff-buildkite-plugin"
executable="monorepo-diff-buildkite-plugin-${kernel}-${arch}"
test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"

if [ -z ${version} ]; then
  url=${repo}/releases/latest/download/${executable}
else
  url=${repo}/releases/download/${version:1}/${executable}
fi

if [[ "$test_mode" == "false" ]]; then
  echo ${url}
  curl -Lf -o ${executable} $url && chmod +x ${executable}
fi

./${executable}
