#!/bin/sh
set -euo pipefail

check_cmd() {
  command -v "$1" > /dev/null 2>&1
  return $?
}

say() {
    local green=`tput setaf 2 2>/dev/null || echo ''`
    local reset=`tput sgr0 2>/dev/null || echo ''`
    echo "$1"
}

err() {
  local red=`tput setaf 1 2>/dev/null || echo ''`
  local reset=`tput sgr0 2>/dev/null || echo ''`
  say "${red}ERROR${reset}: $1" >&2
  exit 1
}

get_architecture() {
  local _ostype="$(uname -s)"
  local _cputype="$(uname -m)"

  RETVAL="$_ostype"_"$_cputype"
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

# This wraps curl or wget.
# Try curl first, if not installed, use wget instead.
downloader() {
  if check_cmd curl; then
    _dld=curl
  elif check_cmd wget; then
    _dld=wget
  else
    _dld='curl or wget' # to be used in error message of need_cmd
  fi

  if [ "$1" = --check ]; then
    need_cmd "$_dld"
  elif [ "$_dld" = curl ]; then
    curl -sSfL "$1" -o "$2"
  elif [ "$_dld" = wget ]; then
    wget "$1" -O "$2"
  else
    err "Unknown downloader"
  fi
}

get_version() {
  local _plugin=${BUILDKITE_PLUGINS:-""}
  local _version=$(echo $_plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".*//')
  RETVAL="$_version"
}

download_binary_and_run() {
  get_architecture || return 1
  local _arch="$RETVAL"

  local _ext=""
  case "$_arch" in
    *windows*)
      _ext=".exe"
      ;;
  esac

  local _executable="monorepo-diff-buildkite-plugin"
  local _repo="https://github.com/monebag/monorepo-diff-buildkite-plugin"

  get_version || return 1
  local _version="$RETVAL"

  if [ -z ${_version} ]; then
    _url=${_repo}/releases/latest/download/${_executable}_${_arch}${_ext}
  else
    _url=${_repo}/releases/download/${_version:1}/${_executable}_${_arch}${_ext}
  fi

  local test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"

  echo $_executable
  if [[ "$test_mode" == "false" ]]; then
    downloader "$_url" "$_executable"

    if [ $? != 0 ]; then
      say "failed to download $_url"
      exit 1
    fi

    chmod +x ${_executable}
  fi

  ./${_executable}
}

download_binary_and_run "$@" || exit 1
